# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IM客户端' do
    use_frameworks!

    pod 'Chatto', '= 3.0.1'
    pod 'ChattoAdditions', '= 3.0.1'
    pod 'Alamofire', '~> 4.4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'SVProgressHUD', '~> 2.1.2'

#    pod 'EFSweetAlert', '~> 0.5.0'

end
